### ISSUE TITLE
Is that allowed to use other training data?

### ISSUE THREAD

**Issue by LegendaryDan** [mrqa/MRQA-Shared-Task-2019#1]
(1) Can we use other QA or MRC training data?
(2) Can we use the training data of non-QA tasks?

Thanks.

**Comment by ajfisch** [comment]
Hello and thank you for the interest! This task is not officially released yet. Please wait for more news later this week.

**Comment by ajfisch** [comment]
Hi @LegendaryDan ,

More details are now available at https://mrqa.github.io/shared.

To answer your questions:
(1) Just the official training sets.
(2) Unlabelled data is allowed. As are off-the-shelf linguistic annotation tools. For other annotated datasets that are not QA datasets, please contact us first. (Post an issue.) We hope to release a whitelist of auxiliary datasets one might consider using.
