### ISSUE TITLE
is there a whitelist of auxiliary datasets?

### ISSUE THREAD

**Issue by LegendaryDan** [mrqa/MRQA-Shared-Task-2019#10]
(1) According to #1, it is encouraged to use unlabeled data. My question is a bit tricky. Is that allowed to use the unlabeled data (i.e. passages only) of the out-of-domain datasets to fine-tune the pre-trained language model? 

(2) Is there any whitelist of labeled non-QA datasets?

**Comment by alontalmor** [comment]
Hi Dan, 

Thanks for reaching out. 

(1) We encourage using unlabelled data, but it seems that fine-tuning on passages only could somewhat overfit to the distribution. 

(2) We have already whitelisted SNLI + MultiNLI, if you have any other dataset in mind you can ask here or send us an email at mrforqa@gmail.com .

Hope this helps,
Alon
