### ISSUE TITLE
What is the default value of timeout of the post request in predict_server?

### ISSUE THREAD

**Issue by LegendaryDan** [mrqa/MRQA-Shared-Task-2019#13]
Is there any default value of timeout of the post request in predict_server.py?

Thanks.

**Comment by robinjia** [comment]
Hi,

There is no explicit timeout value. We ask that your model averages < 1 second per question across the out-of-domain examples (9633 total).

**Comment by robinjia** [comment]
Sorry, forgot to mention this is on our evaluation server, which will have one Titan Xp GPU.
