### ISSUE TITLE
Does the docker that our submission used must support AllenNLP？ I find AllenNLP was used in official evaluate script.

### ISSUE THREAD

**Issue by zhipengChen** [mrqa/MRQA-Shared-Task-2019#15]
![image](https://user-images.githubusercontent.com/13817269/61360032-2b8ecc80-a8b0-11e9-9611-924e55e5112e.png)

**Comment by ajfisch** [comment]
Hi, this would be useful to include as a dependency, as out current evaluation script makes use of some of their utilities for file management.

Let us know if this is not possible.
