### ISSUE TITLE
Is Paddlepaddle DL framework allowed?

### ISSUE THREAD

**Issue by xixiaoyao** [mrqa/MRQA-Shared-Task-2019#2]
we want to use paddlepaddle but confused about if there has been available official image? 
If not, can we use our private docker image? or needed to integrate paddle to codalab image by ourselves?

thanks

**Comment by ajfisch** [comment]
Hi @xixiaoyao,

We will release more details on how to submit to Codalab. The short answer is yes, Codalab does have support for downloading and using docker images. Without knowing much about paddlepaddle myself, I would say I imagine it should be fine.

**Comment by xixiaoyao** [comment]
Thanks @ajfisch ,
 
I wonder if there are limitations about CUDA or CUDNN versions on codalab?

**Comment by ajfisch** [comment]
Good questions. Again, I believe the answer is that as long as you use the proper [docker images](https://github.com/codalab/codalab-worksheets/wiki/Execution#running-jobs-that-use-gpus) it will be fine. We will check and add more details on any caveats soon. Stay tuned.

**Comment by xixiaoyao** [comment]
get it, thanks a lot :)
