### ISSUE TITLE
permission of submission codes

### ISSUE THREAD

**Issue by mtktngch** [mrqa/MRQA-Shared-Task-2019#20]
I have a question regarding submission. (I also send email to mrforqa@gmail.com .)

According to your submission guide, submitted bundles, as well as all dependencies, must be publicly readable.
Unfortunately, it is very difficult to share our codes in public because of our company policy.
So, would it be possible for us to restrict the access of the bundles for public users and allow only organizers to read the bundles?

**Comment by mtktngch** [comment]
Could you tell me the group name of organizers in CodaLab.
The group name of organizers in CodaLab is **mrqa** ?
I will grant all permissions of our bundles to the group of the organizers.

**Comment by robinjia** [comment]
Yes that is correct.
