### ISSUE TITLE
How can I execute allennlp in codalab?

### ISSUE THREAD

**Issue by minstar** [mrqa/MRQA-Shared-Task-2019#22]
Hi, I'm stuck in uploading our submission files.
The main issue is that codalab is compatible with python version 2.7, 
however, allennlp is compatible with python version 3.7.
So, I really tried to execute serve.py, mrqa_official_eval.py and predict_server.py on codalab in various ways but I failed..
Can anyone help me?

**Comment by robinjia** [comment]
Try using the `--request_docker_image` flag in `cl run` to request a different docker image. For our baseline models, we use the docker image `robinjia:mrqa:0.1` (https://hub.docker.com/r/robinjia/mrqa). Be sure to also run your commands with `python3.6`. You can also use your own custom docker image that you upload to dockerhub.

**Comment by minstar** [comment]
Thank you for replying,
I'll try it!!

**Comment by vishalanand** [comment]
@minstar Can you share if you got it running?
And what was the command you used

**Comment by minstar** [comment]
I tried command as below,
```
cl run data_dir:mrqa-dev-data :predict_server.py :mrqa_official_eval.py :bert-cache :baseline "PYTORCH_PRETRAINED_BERT_CACHE=bert-cache python3.6 baseline/serve.py baseline/model.tar.gz 8888 --cude_device 0 & python3.6 predict_server.py <(cat data_dir/*.jsonl) predictions.json 8888; files=$(ls data_dir/*.jsonl); for data_file in ${files}; do base=$(echo ${data_file} | cut -d '/' -f2); python3.6 mrqa_official_eval.py ${data_file} predictions.json > eval_${base::-1}; done" -n run-predictions --request-docker-image robinjia/mrqa:0.1 --request-priority 1 --request_gpus 1
```
but I don't know why the server doesn't work in gpu version in my case.
