### ISSUE TITLE
CUDA device available on codalab

### ISSUE THREAD

**Issue by minstar** [mrqa/MRQA-Shared-Task-2019#24]
Hi, we emptied our minds that CUDA is not available on codalab because of CUDA runtime error.
We almost gave up the submission. 
However, extended submission is possible. So we left this issue.
Is there any way to execute the code with gpu available?
we've got the error as below:
* RuntimeError: cuda runtime error (35) : CUDA driver version is insufficient for CUDA runtime version at /pytorch/torch/csrc/cuda/Module.cpp:53

this issue with bundle ID is 0xa33e129bd4514ebaa65c923b2ad35967.

**Comment by robinjia** [comment]
Hi,

You need to use the flag `--request-gpus 1` when you call `cl run` in order to have a GPU.
