### ISSUE TITLE
Is it still able to evaluate on the test set?

### ISSUE THREAD

**Issue by ikuyamada** [mrqa/MRQA-Shared-Task-2019#27]
Thank you for creating such a great dataset!
I am interested in evaluating my model on this dataset.
Therefore, I would like to ask whether it is still possible to submit the model via Codalab and obtain the scores on the test set.

**Comment by ajfisch** [comment]
Hi! Sorry for the delayed reply. We will make a decision regarding the best format to go forward with continued evaluation on the test set following the workshop.
