### ISSUE TITLE
release of test datasets

### ISSUE THREAD

**Issue by mtktngch** [mrqa/MRQA-Shared-Task-2019#28]
Do you have a plan to release test datasets?

**Comment by ajfisch** [comment]
Hi!

At this time we do not plan to release the test datasets. However, we __do__ continue to support and encourage evaluation via CodaLab! Please contact @robinjia if you would like to evaluate a new system.

**Comment by mtktngch** [comment]
Thank you for your reply.

**Comment by ikuyamada** [comment]
Hi! I would also like to evaluate a system on the test datasets.
Is it ok to follow current instructions to submit a new system?
If not, please provide instructions to run evaluation on the CodaLab.
@robinjia

**Comment by robinjia** [comment]
Yes please follow the current instructions https://worksheets.codalab.org/worksheets/0x926e37ac8b4941f793bf9b9758cc01be
