### ISSUE TITLE
Is that possible to provide baseline performance on in-domain dev set?

### ISSUE THREAD

**Issue by boyang-nlp** [mrqa/MRQA-Shared-Task-2019#3]
Is that possible to provide the performance of the pytorch baseline (with BERT_base and BERT_large) on in-domain dev set? Then, each participant does not need to re-run it if they choose to develop their own system with other framework. Thanks.

**Comment by ajfisch** [comment]
Hi! Yes, we will release both the trained baseline models as well as the results on the in-domain and out-of-domain dev sets next week (May 13). Check back soon!

**Comment by boyang-nlp** [comment]
Thanks!

**Comment by ajfisch** [comment]
Baseline models and results are now available. See the `baseline` directory.
