### ISSUE TITLE
duplicate answers

### ISSUE THREAD

**Issue by mtktngch** [mrqa/MRQA-Shared-Task-2019#6]
I have a question regarding MRQA format.
In some datasets,  I found there are duplicate answers (same spans) for some questons.
Could you explain why it is?

For expamle qid=b0626b3af0764c80b1e6f22c114982c1 in the development data of SQuAD:
```json
 "detected_answers": [
        {
            "text": "Denver Broncos",
            "char_spans": [
                [
                    177,
                    190
                ]
            ],
            "token_spans": [
                [
                    33,
                    34
                ]
            ]
        },
        {
            "text": "Denver Broncos",
            "char_spans": [
                [
                    177,
                    190
                ]
            ],
            "token_spans": [
                [
                    33,
                    34
                ]
            ]
        },
        {
            "text": "Denver Broncos",
            "char_spans": [
                [
                    177,
                    190
                ]
            ],
            "token_spans": [
                [
                    33,
                    34
                ]
            ]
        }
]
```

**Comment by ajfisch** [comment]
This is just a part of the SQuAD dataset, which we took as-is. The reason is that they had multiple human annotators annotate --- there are multiple accepted answers, but they may be all the same.

**Comment by mtktngch** [comment]
I get it. Thanks a lot.

**Comment by jshin49** [comment]
What if the answers are different? For example in the out-of-domain dataset BioASQ or RACE shows multiple different answers for the same question and context. This number is not incorprated into the dataset size you report.
